arb-dir: lib/l10n
output-dir: lib/l10n
synthetic-package: false
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: lib/l10n/untranslated.txt