name: sampleproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Localization dependencies
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Additional dependencies
  auto_route: ^9.2.2
  cupertino_icons: ^1.0.8
  dio: ^5.0.0
  get_it: ^7.6.4
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.16
  injectable: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true  # Enables localization generation

  # Specify assets
  assets:
    - assets/images/

# Flutter localization configuration is managed automatically by flutter gen-l10n
